### ISSUE TITLE
How to work on Nested URL?

### ISSUE THREAD

**Issue by iraycd** [jeffijoe/awilix-router-core#5]
```javascript
prefix('shop/:shop_id').
get('/item/:item_id', 'shop_item')
```

`shop/5c41b7bc52fd6700080461c6/item/5c49c024a72f4c00092a2495/properties`

Any other alternative way around? 
Something like nested routes in https://github.com/alexmingoia/koa-router

**Comment by jeffijoe** [comment]
Afraid not, what would such an API look like, and can it be implemented by all frameworks (Express, Koa)?

**Comment by iraycd** [comment]
**Nested routers in Koa Router.**

```javascript
var forums = new Router();
var posts = new Router();

posts.get('/', (ctx, next) => {...});
posts.get('/:pid', (ctx, next) => {...});
forums.use('/forums/:fid/posts', posts.routes(), posts.allowedMethods());

// responds to "/forums/123/posts" and "/forums/123/posts/123"
app.use(forums.routes());
```

**Comment by jeffijoe** [comment]
Yes I saw that, but how would the `awilix-router-core` API look?

**Comment by iraycd** [comment]
```javascript

const postController =  createController(postApi)
  .prefix('/news')
  .get('', 'find') 
  .get('/:pid', 'get')

export default createController(forumApi)
.use('/forums/:fid/posts', postController);

```

**Comment by jeffijoe** [comment]
Not sure if this is something that should be supported though, such long URLs are kind of an antipattern 😅

You could build it yourself using the utilities from this package perhaps! They are pretty composable.

If this issue gets more attention then I will reconsider it!

**Comment by iraycd** [comment]
@jeffijoe Sorry for not updating you sooner.
I have custom built a own library on top of https://github.com/zensh/route-trie which even support 
Awilix.I will release it soon.

Thank you.
