### ISSUE TITLE
Validating a controller's methods

### ISSUE THREAD

**Issue by davidzwa** [jeffijoe/awilix-router-core#7]
As I'm temporarily using plain NodeJS to migrate old code to `awilix` before moving to Typescript based code, I was wondering if it is possible to implement a startup validation for this module? Currently running into continuous methods which are missing, which Im trying to fix with unit and end-to-end testing (quite a slow method).

Startup validation would basically require looping over and checking whether the controller method or class has the functions indicated in the builder pattern and throwing an error when its missing. Does this sound doable to you? If not, its no problem to close the issue.

**Comment by jeffijoe** [comment]
Its not something I would build in, but you can use the `getStateAndTarget` from `state-util` to look at the configuration and run that yourself.

The controller instance isn't created until a request comes in.

**Comment by davidzwa** [comment]
Perfect and no problem at all!
